apiVersion: 1
datasources:
  - name: cockpit-api
    type: yesoreyeram-infinity-datasource
    uid: cockpit
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      allowedHosts:
        - http://app:8000
